name: backwater
favicon: null
layout_spectrum: 0.53577
typography_spectrum: 0.51806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#ffffff'
    - '#5e4f38'
    - '#708b9e'
    - '#9fb3ba'
  brandStrength: 0.5
  lightness: 0.7849748255684972
  saturation: 0.956547369947657
  rhythmicContrast: 0.25
purpose: []
