name: backwater
favicon: null
layout_spectrum: 0.51203
typography_spectrum: 0.36454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160b09'
    - '#c89b84'
    - '#dfc9cc'
    - '#843b1b'
    - '#890d0d'
  brandStrength: 0.5
  lightness: 0.7849748255684972
  saturation: 0.956547369947657
  rhythmicContrast: 0.25
purpose: []
